language: python
python:
  - "2.7"
  - "3.6"
os: linux
dist: xenial
cache:
  directories:
    - pip
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsystemd-dev
install:
  - pip install -e .[test]
  - pip install coverage
  - pip install coveralls
script:
  - coverage run --source=. -m unittest discover
after_success:
  - coveralls
